# Generated by Django 6.0 on 2025-12-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='link_of_stream',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='لینک استریم'),
        ),
        migrations.AlterField(
            model_name='user',
            name='logo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='avatars/', verbose_name='لوگو'),
        ),
    ]
