# Generated by Django 6.0 on 2025-12-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_description_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='private_code',
            field=models.CharField(default='mlFKbeSsGaSfdbWfeRjJM48gAaGySYn4CAlquW23kckv6ABu4enQnntTTWs4iB2Y1k3Marn5RFZzumCvUrvcCBdRDkY9qHzNAOzvYEzPdtnM1r7nwTyTYxZcnqT6iOoqSFxJKhTpuOTGBd6PAzaAEAp0D9YvpYM5cJUoByBbUJPQf3i0w0mj4IMNx9szEqChwsCCiY6ue56jFNEzlx23iilEuWvwi4r4RdqAQfC4hepJP9O4yIRJR0UmECZ95he', editable=False, max_length=255, verbose_name='کد شناسایی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
    ]
