# Generated by Django 6.0 on 2025-12-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_private_code_alter_user_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='private_code',
            field=models.CharField(default='xtbSLLfKWD3jFnakiEub9WBhfLlt6RGdva4zVoDOj4yEhMkFlXMfZHADmwforrPRcHBLfhD2ieeAGm3PMAc4QLMYcWNrDF7cUkAmkMFFmB6QoNmoFjcSvS0FflnsXXsbT3Uwg5pfImlIIPIMeiaiuHQ4j3ockCrQ2uKHvSSoOp2ezvHf0vJNkdipvEDzgUQWjJYSOxZlTvUH4iFxnKl0OThPh5DJWIYHFGRQYRvhf1TlqPhOpXqb7SxPvuKsTUJ', editable=False, max_length=255, verbose_name='کد شناسایی'),
        ),
    ]
