# Generated by Django 6.0 on 2025-12-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_private_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='private_code',
            field=models.CharField(default='dTeNEuvsW404lBz5yj8ZcZ6EW6MHznCKEQxRgaqDObxbgVIoHd8bUnoZYc0idSzBGK937Dge4lMjIpTPlBnYgPgnv2vsNen0rxXUFHBXi6n30VWc7UDQUUot4BZG4JdcFMpBlh9LTAqs6H9bFmLFhMmWgJwwM4CHplObtbRRXQwHNdykmJXlmE8JmSVqbR5GlBnJ3wqVXcxveLJoKkh3mpMdWPOGIuvR7VbSaP1lkSastgUqRUie9rnS0vxNp6B', editable=False, max_length=255, verbose_name='کد شناسایی'),
        ),
    ]
