# Generated by Django 6.0 on 2025-12-06 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_private_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='private_code',
            field=models.CharField(default='79DL3iu8xMt4Ueh3i6KIRHwnmZPbxQKcuWJjnQc9Ed3mZXrZUTl5GKeuusFCS4Ug9qN6k9kF', editable=False, max_length=255, verbose_name='کد شناسایی'),
        ),
    ]
