# Generated by Django 6.0 on 2025-12-07 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_private_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='private_code',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='کد شناسایی'),
        ),
    ]
